//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.Return_Stock = new HashSet<Return_Stock>();
            this.StockUp = new HashSet<StockUp>();
        }
    
        public string Goods_ID { get; set; }
        public string Brand_Name { get; set; }
        public string Goods_Name { get; set; }
        public string Goods_Colour { get; set; }
        public string Goods_Size { get; set; }
        public string Goods_Material { get; set; }
        public string Goods_Clean { get; set; }
        public string Goods_Season { get; set; }
        public string Goods_MadeBy { get; set; }
        public string Goods_Sum_Number { get; set; }
        public string Goods_ramarks { get; set; }
        public string Goods_danjia { get; set; }
    
        public virtual ICollection<Return_Stock> Return_Stock { get; set; }
        public virtual ICollection<StockUp> StockUp { get; set; }
    }
}
