//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notemanagementEntities : DbContext
    {
        public notemanagementEntities()
            : base("name=notemanagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<LoginUser> LoginUser { get; set; }
        public virtual DbSet<Return_Stock> Return_Stock { get; set; }
        public virtual DbSet<Sales_Return> Sales_Return { get; set; }
        public virtual DbSet<Season> Season { get; set; }
        public virtual DbSet<sell> sell { get; set; }
        public virtual DbSet<size> size { get; set; }
        public virtual DbSet<StockUp> StockUp { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
