//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Stock
    {
        public string Document_ID { get; set; }
        public string Date { get; set; }
        public string Goods_ID { get; set; }
        public string Goods_Number { get; set; }
        public string Goods_danjia { get; set; }
        public string Due { get; set; }
        public string Real_Payment { get; set; }
        public string Supplier_ID { get; set; }
        public string Worker_ID { get; set; }
        public string Account { get; set; }
        public string Return_Remark { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
