//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Return
    {
        public string Document_ID { get; set; }
        public string Document_ID_old1 { get; set; }
        public string Goods_ID11 { get; set; }
        public string Goods_Number11 { get; set; }
        public string Goods_ID12 { get; set; }
        public string Goods_Number12 { get; set; }
        public string Goods_ID13 { get; set; }
        public string Goods_Number13 { get; set; }
        public string Goods_ID14 { get; set; }
        public string Goods_Number14 { get; set; }
        public string Goods_ID15 { get; set; }
        public string Goods_Number15 { get; set; }
        public string Goods_ID16 { get; set; }
        public string Goods_Number16 { get; set; }
        public string Goods_sum1 { get; set; }
        public string docu_old_2 { get; set; }
        public string Gid21 { get; set; }
        public string gn21 { get; set; }
        public string gid22 { get; set; }
        public string dm22 { get; set; }
        public string gid23 { get; set; }
        public string gn23 { get; set; }
        public string gid24 { get; set; }
        public string gn24 { get; set; }
        public string gid25 { get; set; }
        public string gn25 { get; set; }
        public string gid26 { get; set; }
        public string gn26 { get; set; }
        public string gs2 { get; set; }
        public string docu_old_3 { get; set; }
        public string gid31 { get; set; }
        public string gn31 { get; set; }
        public string gid32 { get; set; }
        public string gn32 { get; set; }
        public string gid33 { get; set; }
        public string gn33 { get; set; }
        public string gid34 { get; set; }
        public string gn34 { get; set; }
        public string gid35 { get; set; }
        public string gn35 { get; set; }
        public string gid36 { get; set; }
        public string gn36 { get; set; }
        public string gs3 { get; set; }
        public string docu_old_4 { get; set; }
        public string gid41 { get; set; }
        public string gn41 { get; set; }
        public string gid42 { get; set; }
        public string gn42 { get; set; }
        public string gid43 { get; set; }
        public string gn43 { get; set; }
        public string gid44 { get; set; }
        public string gn44 { get; set; }
        public string gid45 { get; set; }
        public string gn45 { get; set; }
        public string gid46 { get; set; }
        public string gn46 { get; set; }
        public string gs4 { get; set; }
        public string docu_old_5 { get; set; }
        public string gid51 { get; set; }
        public string gn51 { get; set; }
        public string gid52 { get; set; }
        public string gn52 { get; set; }
        public string gid53 { get; set; }
        public string gn53 { get; set; }
        public string gid54 { get; set; }
        public string gn54 { get; set; }
        public string gid55 { get; set; }
        public string gn55 { get; set; }
        public string gid56 { get; set; }
        public string gn56 { get; set; }
        public string gs5 { get; set; }
        public string docu_old_6 { get; set; }
        public string gid61 { get; set; }
        public string gn61 { get; set; }
        public string gid62 { get; set; }
        public string gn62 { get; set; }
        public string gid63 { get; set; }
        public string gn63 { get; set; }
        public string gid64 { get; set; }
        public string gn64 { get; set; }
        public string gid65 { get; set; }
        public string gn65 { get; set; }
        public string gid66 { get; set; }
        public string gn66 { get; set; }
        public string gs6 { get; set; }
        public string due { get; set; }
        public string real_payment { get; set; }
        public string Client_ID { get; set; }
        public string Worker_ID { get; set; }
        public string Account { get; set; }
        public string Sell_Remark { get; set; }
    }
}
