//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class sell
    {
        public string Document_ID { get; set; }
        public string Goods_ID1 { get; set; }
        public string Goods_danjia1 { get; set; }
        public string Goods_Number1 { get; set; }
        public string Goods_ID2 { get; set; }
        public string Goods_danjia2 { get; set; }
        public string Goods_Number2 { get; set; }
        public string Goods_ID3 { get; set; }
        public string Goods_danjia3 { get; set; }
        public string Goods_Number3 { get; set; }
        public string Goods_ID4 { get; set; }
        public string Goods_danjia4 { get; set; }
        public string Goods_Number4 { get; set; }
        public string Goods_ID5 { get; set; }
        public string Goods_danjia5 { get; set; }
        public string Goods_Number5 { get; set; }
        public string Goods_ID6 { get; set; }
        public string Goods_danjia6 { get; set; }
        public string Goods_Number6 { get; set; }
        public string Due { get; set; }
        public string Real_Payment { get; set; }
        public string Client_ID { get; set; }
        public string Worker_ID { get; set; }
        public string Account { get; set; }
        public string Sell_Remarks { get; set; }
    }
}
