//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Return_Stock = new HashSet<Return_Stock>();
            this.StockUp = new HashSet<StockUp>();
        }
    
        public string Worker_ID { get; set; }
        public string Worker_Name { get; set; }
        public string Worker_Phone { get; set; }
        public string Worker_Email { get; set; }
        public string Worker_Bumen { get; set; }
    
        public virtual ICollection<Return_Stock> Return_Stock { get; set; }
        public virtual ICollection<StockUp> StockUp { get; set; }
    }
}
